#!/bin/sh

# Get files
FILES=$(git diff --cached --name-only | grep -E "(.js[x]?)$")

if [ "${FILES}" = "" ]; then
  exit 0
fi

# Run linting
$(npm bin)/eslint ${FILES}

if [ "$?" != 0 ]; then
  echo "ERROR: Commit failed! Check eslint hints."
      
  exit 1 # reject
fi

echo "SUCCESS: eslint passed! Commit done."

exit 0
